export {default as Footer} from './main/Footer'
export {default as Header} from './main/Header'
export {default as Moq} from './self/Moq'
export {default as Fact} from './self/Fact'
export {default as Pay} from './self/Pay'
export {default as Pays} from './location/Pays'
export {default as Exchange} from './self/Exchange'
export {default as Htc} from './location/Htc'
export {default as Fly} from './transport/Fly'
export {default as Boat} from './transport/Boat'
export {default as Swap} from './transport/Swap'

